datasource:
  pages:
    home:
      - config1.yml
      - config2.yml
    about:
      - []

  urls:
    /products:
      - config1.yml
      - config2.yml  # Uses both config1.yml and config2.yml
    /orders:
      - config1.yml

  hosts:
    example.com:
      - config1.yml
    another-example.com:
      - config2.yml